=== walle1027/framework/framework-common/src/main/resources/mapping.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="http://www.shyueya.com/mappings"
		   targetNamespace="http://www.shyueya.com/mappings">
	<xs:element name="mappings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mapping" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="srcClass" type="xs:string" maxOccurs="1"/>
							<xs:element name="destClass" type="xs:string" maxOccurs="1"/>
							<xs:element name="excludes">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="exclude" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="srcProperty" type="xs:string" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="srcType" type="xs:string"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="destProperty" type="xs:string" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="destType" type="xs:string"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="includs">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="include" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="srcProperty" type="xs:string" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="srcType" type="xs:string"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="destProperty" type="xs:string" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="destType" type="xs:string"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="convertor" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string"/>
						<xs:attribute name="srcClass" type="xs:string"/>
						<xs:attribute name="destClass" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== walle1027/framework/framework-common/src/test/resources/org/loed/framework/common/mapping/mapings-simple.xml
<?xml version="1.0" encoding="utf-8"?>
<mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xmlns="http://www.yangtao.org/mapping"
		  xsi:noNamespaceSchemaLocation="/mapping.xsd">
	<!--属性映射配置文件 direction=one-way ,two-way-->
	<mapping srcClass="org.loed.framework.common.mapping.ClassA">
		<excludes>
			<exclude>
				<srcProperty>id</srcProperty>
			</exclude>
			<exclude>
				<srcProperty>version</srcProperty>
			</exclude>
			<exclude>
				<srcProperty>name</srcProperty>
			</exclude>
		</excludes>
	</mapping>
	<mapping id="excludeSimple" srcClass="org.loed.framework.common.mapping.ClassA">
		<excludes>
			<exclude>
				<srcProperty>id</srcProperty>
			</exclude>
			<exclude>
				<srcProperty>version</srcProperty>
			</exclude>
			<s></s>
		</excludes>
	</mapping>
</mappings>
